apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: MoreStages
  annotations:
    alauda.io/displayName.zh-CN: 有好多好多stage有好多好多stage有好多好多stage
    alauda.io/displayName.en: Build docker image
    alauda.io/description.zh-CN: 有好多好多stage
    alauda.io/description.en: Clone code and builds a docker image
    alauda.io/readme.zh-CN: 有好多好多好多好多stage
    alauda.io/readme.en: Clone code and builds a docker image
    alauda.io/version: v0.15
    alauda.io/style.icon: build
  labels:
    category: CI
spec:
  engine: graph
  withSCM: true
  stages:
    - name: Clone
      tasks:
        - name: clone
          kind: PipelineTaskTemplate 
    - name: alaudawithoutCI
      tasks:
        - name: alaudawithoutCI
          kind: PipelineTaskTemplate
    - name: alaudaBuildImage
      tasks:
        - name: alaudaBuildImage
          kind: PipelineTaskTemplate
    - name: Task1
      tasks:
        - name: clone
          kind: PipelineTaskTemplate 
    - name: Task2
      tasks:
        - name: alaudawithoutCI
          kind: PipelineTaskTemplate
    - name: Task3
      tasks:
        - name: alaudaBuildImage
          kind: PipelineTaskTemplate
    - name: Task4
      tasks:
        - name: clone
          kind: PipelineTaskTemplate 
    - name: Task5
      tasks:
        - name: alaudawithoutCI
          kind: PipelineTaskTemplate
    - name: Task6
      tasks:
        - name: alaudaBuildImage
          kind: PipelineTaskTemplate
    - name: Task7
      tasks:
        - name: clone
          kind: PipelineTaskTemplate 
    - name: Task8
      tasks:
        - name: alaudawithoutCI
          kind: PipelineTaskTemplate
    - name: Task9
      tasks:
        - name: alaudaBuildImage
          kind: PipelineTaskTemplate
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: "CIEnbale"
          schema:
            type: boolean
          binding:
            - BuildImage.args.CIEnbale
          display:
            type: boolean
            name:
              zh-CN: "CI开关1"
              en: "CI enable"
          required: false
          default: ""
        - name: "dockerfilePath"
          schema:
            type: string
          binding:
            - BuildImage.args.dockerfilePath
          display:
            type: string
            name:
              zh-CN: "Dockerfile路径"
              en: "Dockerfile's path"
          required: true
          default: ./
        - name: "contextDir"
          schema:
            type: string
          binding:
            - BuildImage.args.contextDir
          display:
            type: string
            name:
              zh-CN: "构建路径"
              en: "Build context"
          required: true
          default: ./
    - displayName:
        zh-CN: 配置镜像仓库 
        en: Image Repository Configuration
      items:
        - name: "image"
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - BuildImage.args.image
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "镜像仓库"
              en: "Image repository"
            description:
              zh: "构建生成的镜像"
              en: "Image repository to store the built image"
          required: true
        - name: "imageTag"
          schema:
            type: string
          binding:
            - BuildImage.args.imageTag
          display:
            type: string
            name:
              zh-CN: "镜像版本"
              en: "Customized image tag"
          default: "latest"
          required: true
        - name: imageExtraTag
          schema:
            type: string
          binding:
            - BuildImage.args.imageExtraTag
          display:
            type: string
            name:
              zh-CN: "附加版本"
              en: "Auto generated tag"
          required: false
        - name: imageRegistryCredentialsId
          schema:
            type: string
          binding:
            - BuildImage.args.imageRegistryCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            related: jenkins_integration_id
            name:
              zh-CN: "镜像中心凭据"
              en: "Registry credentials"
          required: false
        - name: "useImageCache"
          schema:
            type: boolean
          binding:
            - BuildImage.args.useImageCache
          display:
            type: boolean
            name:
              zh-CN: "开启镜像缓存"
              en: "Use image cache"
          default: ""
          required: true
